version: '3.7'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 1337:8000
    environment:
      - DEBUG=1
      - RUNNING_FROM_DOCKER=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - web-php
      #- mysqldb
      - mariadb
      - redis
      - sendria
      # - celery
      # - celery-beat
  web-php:
    build: ./jacustom
    volumes:
      - ./jacustom/:/var/www/html/
    ports:
      - 1338:80
    depends_on:
      #- mysqldb
      - mariadb
#  mysqldb:
#    image: mysql:5.7
#    restart: always
#    ports:
#      - '3306:3306'
#    environment:
#      MYSQL_HOST: 'localhost'
#      MYSQL_DATABASE: 'johnamico'
#      MYSQL_USER: 'root'
#      MYSQL_PASSWORD: 'root'
#      MYSQL_ROOT_PASSWORD: 'root'
#    volumes:
#      - "./engine_resources/db_data:/var/lib/mysql"
  mariadb:
    image: mariadb:10.2
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_HOST: 'localhost'
      MYSQL_DATABASE: 'johnamico'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - "./engine_resources/db_data:/var/lib/mysql"
  sendria: # MailCather
    image: msztolcman/sendria:v2.0.1.0
    ports:
      - '1325:1025'
      - '1380:1080'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  celery:
    build: ./project
    command: celery -A core worker -l info
    volumes:
      - ./project/:/code/
    depends_on:
      - redis
  celery-beat:
    build: ./project
    command: celery -A core beat -l info --pidfile=
    volumes:
      - ./project/:/code/
    depends_on:
      - redis
